### ISSUE TITLE
Cant make it works, unknown error 

### ISSUE THREAD

**Issue by Oniriik** [seanbudd/discord-email-verification#4]
Hey ! i've tried to follow your steps but idk, i got errors 

[Error img](https://i.ibb.co/X8ft7pF/Screenshot-from-2022-04-19-02-08-39.png])

says "app not responding"

[config.js img](https://i.ibb.co/Fhh50sN/index.png])

If you could add me on discord for help could be awesome : Oniriik#2908

**Comment by seanbudd** [comment]
Hi @Oniriik - I couldn't find your discord tag, are you sure it's correct?

Are there any errors logged from the console running `npm start`?

**Comment by Oniriik** [comment]
mb the good one is 

OniriiK#2908

Nop console just say running and logged
